# -*- coding: utf-8 -*-
"""Titanic_pro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UoJbt-Hm0qKdE2D2jqviTQjI74eNOX-u

import pandas as pd
"""

import pandas as pd

data = pd.read_csv('train.csv')
data

import seaborn as sns

sns.countplot(x='Survived',data=data)

sns.scatterplot(x='Age',y='Fare',data=data)
data.columns

average = data.groupby('Pclass')['Age'].mean()
average

data.groupby('Sex')['Survived'].mean()

#select only numeric columns

numerical_columns = data.select_dtypes(include=['float64','int64'])
numerical_columns

#afficher la matrice de Corrélation

matrice = numerical_columns.corr()
matrice



sns.heatmap(matrice, annot=True,cmap='coolwarm')