# -*- coding: utf-8 -*-
"""Titanic_pro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UoJbt-Hm0qKdE2D2jqviTQjI74eNOX-u
"""

import pandas as pd

data = pd.read_csv('train.csv')
data.columns

data.isnull().sum()

for data in data.columns:
  print(data)
  print(data.dtype)